[package]
name = "edgehome-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "edgehome"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
edgehome-config = { path = "../edgehome-config" }
serde_json.workspace = true

