[package]
name = "edgehome-ollama"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
edgehome-config = { path = "../edgehome-config" }
edgehome-core = { path = "../edgehome-core" }
edgehome-parser = { path = "../edgehome-parser" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
